### ISSUE TITLE
Parse parameter getting exclusive

### ISSUE THREAD

**Issue by TeebObeeT** [benjypng/logseq-quicktodo-plugin#10]
Hello,

When I set the parse parameter in the settings, if I try to insert a todo without a link, then it won't be created at all. My expectation would be to insert it on my journal page in this case.

**Comment by benjypng** [comment]
This function has been deprecated.

Instead, if you want to send an item to a [[mentioned page]], you can use Cmd/Ctrl + Enter.

**Comment by TeebObeeT** [comment]
Indeed, thanks and sorry!

**Comment by benjypng** [comment]
no need for any apologies at all!
