### ISSUE TITLE
Focus input field when opening the prompt

### ISSUE THREAD

**Issue by thinkh** [benjypng/logseq-quicktodo-plugin#11]
When I type `m t` the prompt to enter my todo opens. However, I still must click with the mouse into the input field to start typing.

It would be very helpful if the input field is focused automatically and I can start typing right away.

**Comment by benjypng** [comment]
You can actually start typing (at least this is how it works on my instance).
Could you try trying `m t` then immediately start typing something? It should immediately appear in the TODO box.

**Comment by thinkh** [comment]
Ah, yes! I just did not see a blinking text cursor. That's why assumed that the input is not highlighted. Could you do anything about this? If not, you can also close this issue.

![logseq](https://user-images.githubusercontent.com/5851088/172474299-29489457-866f-4482-a9c5-0b3bf5509526.gif)

**Comment by benjypng** [comment]
Available in v1.8.2!

**Comment by thinkh** [comment]
Thanks! 👍
