### ISSUE TITLE
Bug: TODO's not added to journal with yyyy/MM/dd format

### ISSUE THREAD

**Issue by cesar-programs** [benjypng/logseq-quicktodo-plugin#12]
Hello, 

I found that adding TODOs to the daily journal page is not working as intended when the date format is different than MMM do, yyyy. 

I also changed the format in the JSON file, but it didn't work. 

Thank you.

**Comment by benjypng** [comment]
Can you provide an example please?

**Comment by cesar-programs** [comment]
Hello, hkgnp. 

I tested it today, and it worked fine. So I'm not sure what was occurring at the time of my original report. 

Thank you.
