### ISSUE TITLE
'Reload' and how to enter the new todo

### ISSUE THREAD

**Issue by L0cutus** [benjypng/logseq-quicktodo-plugin#2]
is it ok tha a plugin loaded from source keep show the 'Reload' message?
![Schermata del 2022-01-29 09-30-18](https://user-images.githubusercontent.com/90012/151654061-6670ea44-132a-4419-a722-d5a6e9f30ee5.png)

When i press the cmd+shift+p + quick+enter and type the message, even if i type enter (for example "add this to [[Stefano]]" + ENTER)
nothing happens.

**Comment by benjypng** [comment]
Hmm please try the steps below

1. Click on the wrench and click Uninstall
2. Restart Logseq
3. Go to marketplace and install the plugin from there
4. Restart Logseq
5. Press Ctrl+Shift+P, type “quick”, select the first option, type your
task then press Enter.

**Comment by L0cutus** [comment]
> Hmm please try the steps below 1. Click on the wrench and click Uninstall 2. Restart Logseq 3. Go to marketplace and install the plugin from there 4. Restart Logseq 5. Press Ctrl+Shift+P, type “quick”, select the first option, type your task then press Enter.
> […](#)

not present for now in marketplace i'll wait :)

**Comment by benjypng** [comment]
Oooo! Didn’t realise. Haha.
You can try the one in the marketplace now! It's now there.

**Comment by L0cutus** [comment]
Ok i have done but the problem still persist, ENTER key still does not work into input field

**Comment by benjypng** [comment]
Could you share more about the steps that you have taken? E.g.

1. Ctrl+Shift+P to open up command palette
2. Type quick and choose the first option
3. Type your task
4. Press Enter

**Comment by garyo** [comment]
I am having the same issue. Exactly your workflow. Using logseq nightly on Windows, version from 20220129.
1. Ctrl+Shift+P to open palette
2. type "quick", choose quick todo
3. Task box opens at top of window; type my task in there
4. Press Enter -- nothing happens.
5. Tried Ctrl+Enter, Alt+Enter, Shift+Enter; none of them do anything.
6. Eventually use ESC to go back to main window.

In the dev tools I see this error when I hit Enter:
```
index.705bb033.js:2 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'name')
    at n (index.705bb033.js:2)
```
When I pretty-print that file, the code in question looks like this. I think `r.name` is the failing object.
```javascript
                )(new Date, logseq.settings.preferredDateFormat)
                  , r = await logseq.Editor.getPage(n.substring(2, n.length - 2));
                logseq.settings.defaultPage ? await logseq.Editor.insertBlock(logseq.settings.defaultPage.toLowerCase(), `TODO ${e}`, {
                    isPageBlock: !0
                }) : await logseq.Editor.insertBlock(r.name, `TODO ${e}`, {
                    isPageBlock: !0
                }),
                t(""),
                logseq.hideMainUI({
                    restoreEditingCursor: !0
                }),
                logseq.App.showMsg(`${e} added to today's journal page!`)
```

**Comment by benjypng** [comment]
@garyo Thanks for the error message! That was very helpful.

I've implemented a fix @garyo @L0cutus. Do download the latest update and see if it's ok now. Please remember to restart after updating.

**Comment by garyo** [comment]
Update (1.3) no longer gives the error, and Enter works -- I get the confirmation message. But I don't actually see the TODO in my journal. I grepped all my logseq files and don't see it anywhere, sorry. 
I do get this error when starting the plugin:
![image](https://user-images.githubusercontent.com/139975/152044472-c95134b2-d699-4fde-bba6-74224948bccf.png)
I don't know if that is significant. I won't use any kbd shortcuts for this plugin anyway, since it pops up that nice menu when I select text.

**Comment by benjypng** [comment]
@garyo Oh dear! Hmm, could you share your date format in Logseq, please?

**Comment by garyo** [comment]
`:journal/page-title-format "yyyy/MM/dd, E"`

**Comment by benjypng** [comment]
Thanks. Can I confirm that your date looks like the below in Logseq?

<img width="321" alt="Screenshot 2022-02-02 at 10 35 06 AM" src="https://user-images.githubusercontent.com/47936793/152084598-f9e2697e-c494-4f37-8013-d2f90cfa1ed9.png">

If not, can you show me how you managed to do it as when I set to "yyyy/MM/dd, E", the above shows up. This causes the error because the plugin is trying to find "yyyy/MM/dd, E" but the pages are still in "yyyy/MM/dd, EEE". 

If you change your format to "yyyy/MM/dd, EEE", it would immediately work.

**Comment by garyo** [comment]
Yes, exactly:
![image](https://user-images.githubusercontent.com/139975/152087403-4c4e070b-aa3e-4b04-9520-4ab751303162.png)

**Comment by benjypng** [comment]
Yeah I guessed as much. If it’s really E the. It should end with a “T”.

If you change it from “E” to “EEE” it will work.

**Comment by garyo** [comment]
Thanks, yes that does work! (Perhaps you should give an error if something goes wrong?)

**Comment by benjypng** [comment]
Actually I didn’t know of this bug until you reported! Hence there isn’t an
error per se because it expects something from Logseq which is correct.

I’ll file a bug report with Logseq too.

**Comment by L0cutus** [comment]
> @garyo Thanks for the error message! That was very helpful.
> 
> I've implemented a fix @garyo @L0cutus. Do download the latest update and see if it's ok now. Please remember to restart after updating.

this solved for me the "ENTER" do not working problem thanks !
