### ISSUE TITLE
What about to add also the ability to...

### ISSUE THREAD

**Issue by L0cutus** [benjypng/logseq-quicktodo-plugin#4]
Add the text DIRECTLY into the page project indicated (not on the journal i mean) and if it doesn't exists to create it?

**Comment by benjypng** [comment]
Sorry what do you mean?

**Comment by L0cutus** [comment]
Let's say you have a [[Project A]] page and a [[Project B]] page and you are currently editing the [[Project A]] page, when you call the command palette and type the 'quick' command, if you type eg.

"This is a new event that must be on the [[Project B]] page" + ENTER

This line must not be journaled BUT your plugin must check if the page [[Project B]] exists, if it exists it must write all the text, in that page, if the page does not exist, create it and add the text.

Sorry for my poor English language...

**Comment by benjypng** [comment]
> Let's say you have a [[Project A]] page and a [[Project B]] page and you are currently editing the [[Project A]] page, when you call the command palette and type the 'quick' command, if you type eg.
> 
> "This is a new event that must be on the [[Project B]] page" + ENTER
> 
> This line must not be journaled BUT your plugin must check if the page [[Project B]] exists, if it exists it must write all the text, in that page, if the page does not exist, create it and add the text.
> 
> Sorry for my poor English language...

Have added this feature in v1.4 in the marketplace.

**Comment by L0cutus** [comment]
Great thanks, What about:

"This is a new event that must be on the [[Project B]] page" + ENTER  -->> add to journal
"This is a new event that must be on the [[Project B]] page" + (ctrl+ENTER) -->> add to page ?

instead to choose from config in a more rigid way?

**Comment by benjypng** [comment]
@L0cutus available now in v1.4.0 as above. Just need to ensure that your settings file does not include the "parse" attribute.

**Comment by L0cutus** [comment]
> @L0cutus available now in v1.4.0 as above. Just need to ensure that your settings file does not include the "parse" attribute.

GREAT thanks !
