### ISSUE TITLE
In between state after insertion

### ISSUE THREAD

**Issue by TeebObeeT** [benjypng/logseq-quicktodo-plugin#8]
Hello,

I explain the whole context there: https://www.reddit.com/r/logseq/comments/u8px7u/fire_forget/

After inserting a todo by using, my logseq is in a "in between" state where I can't press enter to edit, esc to navigate or use any shortcut (including the "m t" to add another todo).

Note that this behavior might not be only caused by your plugin.

**Comment by benjypng** [comment]
Fixed in v1.8.0.
