### ISSUE TITLE
Ctrl + A is already useful

### ISSUE THREAD

**Issue by TeebObeeT** [benjypng/logseq-quicktodo-plugin#9]
Hello,

Ctrl+A is a shortcut that is already usefull (select all, might be to copy the text somewhere else for example). Could this be made a parameter in the settings ?

**Comment by benjypng** [comment]
Good point.

Toggle shortcut has been changed to Cmd/Ctrl + t instead.

**Comment by TeebObeeT** [comment]
Thanks! 8-) Awesome
